# name: remote ssh command
# on: [push]
# jobs:

#   build:
#     name: Build
#     runs-on: ubuntu-latest
#     steps:
#     - name: executing remote ssh commands using password
#       uses: appleboy/ssh-action@master
#       with:
#         host: 213.205.81.6
#         username: root
#         key: ${{ secrets.SSH_PRIVATE_KEY }}
#         port: 1330
#         script: |
#           cd /sites/webapps/public/
#           ls

name: Node CI funciona

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16'
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build --if-present
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/"
          REMOTE_HOST: 213.205.81.6
          REMOTE_PORT: 1330
          REMOTE_USER: root
          TARGET: /sites/webapps/teste/
          EXCLUDE: "/dist/, /node_modules/"